apiVersion: v1
kind: Pod
metadata:
    labels:
        schedulize.preflight.guco.zszazi.github.io: "true" #Schedule + Analyze = Schedulize
    name: nginx-safe
spec:
    containers:
        - image: nginx:1.27.3-alpine3.20-slim
          name: nginx-safe
---
apiVersion: v1
kind: Pod
metadata:
   name: nginx-normal #No Scan No Kata
spec:
   containers:
       - image: nginx:1.27.3-alpine3.20-slim
         name: nginx-normal
---
apiVersion: v1
kind: Pod
metadata:
    labels:
        schedulize.preflight.guco.zszazi.github.io: "true" #Schedule + Analyze = Schedulize
    name: nginx-unsafe
spec:
    containers:
        - image: nginx:1.21.0-alpine
          name: nginx-unsafe